import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

import MovingTitle from "../Components/MovingTitle";
import Project from "../Components/Project";

import { Slide, Zoom } from "react-awesome-reveal";

export default function Home() {
  const projects = [
    {
      id: "1",
      name: "LUXURY PERSPECTIVE ",
      imgUrl:
        "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg",
    },
    {
      id: "2",
      name: "LUXURY PERSPECTIVE ",
      imgUrl:
        "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg",
    },
    {
      id: "3",
      name: "LUXURY PERSPECTIVE ",
      imgUrl:
        "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg",
    },
  ];

  return (
    <div className={styles.home}>
      <Head>
        <title>Brkic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Section */}

      <div className={styles.main}>
        <div className={styles.text}>
          <h1 className={styles.outline}>HELLO, I AM</h1>
          <h1>ANTONIO</h1>
        </div>
        <div className={styles.contact}>
          <Link href="/contact">
            <div className={styles.button}>
              <img src="/icons/contactMeRounded.svg" className={styles.text} />
              <img src="/icons/phone.svg" className={styles.phone} />
            </div>
          </Link>
          <p>
            {
              "I am a web developer based in Croatia and specialized in professional Real Estate websites"
            }
          </p>
        </div>
      </div>

      {/* Who Am I Section */}

      <div className={styles.who}>
        <MovingTitle
          text="WHO AM I?"
          color="#867874"
          spacing={50}
          speed={0.5}
        />
        <div className={styles.text}>
          <Slide triggerOnce cascade>
            <h1 className={styles.outline}>I AM</h1>
            <p>
              {
                "Antonio Brkic, Real Estate web developer. I develop websites for Real Estate agents, apartments and hotels. I always had passion for programming and web development."
              }
            </p>
          </Slide>
        </div>
      </div>

      {/* My Work Section */}

      <div className={styles.work}>
        <MovingTitle text="MY WORK" color="#e4e4e4" spacing={50} speed={0.5} />
        <div className={styles.container}>
          {projects.map((project) => (
            <Project project={project} key={project.id} />
          ))}
        </div>
      </div>

      {/* Ready To Work Section */}
      <div className={styles.ready}>
        <h2>READY TO</h2>
        <h1 className={styles.outline}>WORK?</h1>
        <p>{"Get in touch with me and I will start working instantly."}</p>
        <Zoom triggerOnce>
          <button>{"LET'S WORK!"}</button>
        </Zoom>
      </div>
    </div>
  );
}
