import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

import MovingTitle from "../Components/MovingTitle";
import Project from "../Components/Project";

import { Slide, Zoom, Fade } from "react-awesome-reveal";
import TypeAnimation from "react-type-animation";

export default function Home() {
  const projects = [
    {
      id: "1",
      name: "LUXURY PERSPECTIVE ",
      imgUrl:
        "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg",
    },
    {
      id: "2",
      name: "LUXURY PERSPECTIVE ",
      imgUrl:
        "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg",
    },
    {
      id: "3",
      name: "LUXURY PERSPECTIVE ",
      imgUrl:
        "https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg",
    },
  ];

  return (
    <div className={styles.home}>
      <Head>
        <title>Brkic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Section */}

      <div className={styles.main}>
        <div className={styles.text}>
          <h1 className={styles.outline}>HELLO, I AM</h1>
          <TypeAnimation
            cursor={true}
            sequence={["ANTONIO", 3000, "WEB DEVELOPER", 3000]}
            wrapper="h1"
            repeat={Infinity}
          />
        </div>
        <div className={styles.contact}>
          <Link href="/contact">
            <Fade triggerOnce>
              <div className={styles.button}>
                <img
                  src="/icons/contactMeRounded.svg"
                  className={styles.text}
                />
                <img src="/icons/phone.svg" className={styles.phone} />
              </div>
            </Fade>
          </Link>
        </div>
        <div className={styles.image}></div>
      </div>

      {/* Who Am I Section */}

      <div className={styles.who}>
        <MovingTitle
          text="WHO AM I?"
          color="#AEA9A5"
          spacing={50}
          speed={0.5}
        />
        <div className={styles.text}>
          <Slide triggerOnce cascade>
            <h1 className={styles.outline}>I AM</h1>
            <p>
              {
                "Antonio Brkic, Real Estate web developer. I develop websites for Real Estate agents, apartments and hotels. I always had passion for programming and web development."
              }
            </p>
          </Slide>
        </div>
      </div>

      {/* My Work Section */}

      <div className={styles.work}>
        <MovingTitle text="MY WORK" color="#2C2B30" spacing={50} speed={0.5} />
        <div className={styles.container}>
          {projects.map((project) => (
            <Project project={project} key={project.id} />
          ))}
        </div>
      </div>

      {/* Ready To Work Section */}
      <div className={styles.ready}>
        <h2>READY TO</h2>
        <h1 className={styles.outline}>WORK?</h1>
        <p>{"Get in touch with me and I will start working instantly."}</p>
        <Zoom triggerOnce>
          <Link href="/contact">
            <button>{"LET'S WORK!"}</button>
          </Link>
        </Zoom>
      </div>
    </div>
  );
}
